development:
  adapter: postgresql
  encoding: unicode
  database: employee_management
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: employee_management
  pool: 5
  username: postgres
  password: postgres